export const sampleMentors = [
    {
      _id: 'm1',
      name: 'Asha Singh',
      email: 'asha@example.com',
      bio: 'Full stack developer and career mentor with 7 years experience.',
      country: 'India',
      state: 'Karnataka',
      city: 'Bengaluru',
      profileImg: '',
      language: ['English', 'Hindi'],
      skills: ['React', 'Node.js', 'System Design'],
      meetingCharge: 500,
      availability: 'Weekdays 6-9 PM IST',
      status: 'pending',
      linkedInURL: 'https://linkedin.com/in/ashasingh',
      gender: 'Female',
      highestEducation: 'B.Tech Computer Science',
      workExperience: '7 years',
      currentJob: 'Senior Engineer at Acme',
      socialMediaLinks: ['https://twitter.com/asha'],
      documents: [{ name: 'Resume.pdf', url: '#' }],
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'm2',
      name: 'Ravi Kumar',
      email: 'ravi@example.com',
      bio: 'Backend engineer and mentor for Node.js and databases.',
      country: 'India',
      state: 'Delhi',
      city: 'New Delhi',
      profileImg: '',
      language: ['English'],
      skills: ['Node.js', 'MongoDB', 'SQL'],
      meetingCharge: 0,
      availability: 'Weekends',
      status: 'pending',
      linkedInURL: '',
      gender: 'Male',
      highestEducation: 'MCA',
      workExperience: '5 years',
      currentJob: 'Backend Engineer at ExampleCo',
      socialMediaLinks: [],
      documents: [],
      createdAt: new Date().toISOString(),
    },
  ]
  